# Killswitch and private network, LAN, access.

[Interface]
PrivateKey = 123213123123123123123123123123123=
Address = 101.101.101.3/32
DNS = 199.99.0.1, 199.99.0.2

# Add Routes for private networks
PostUp = /bin/sh -c "ip route add 192.168.0.0/16 via $(ip route | grep default | awk '{print $3}') dev eth0 || true"
PostUp = /bin/sh -c "ip route add 172.16.0.0/12 via $(ip route | grep default | awk '{print $3}') dev eth0 || true"
PostUp = /bin/sh -c "ip route add 10.0.0.0/8 via $(ip route | grep default | awk '{print $3}') dev eth0 || true"

#Add killswitch iptables rules
PostUp = /config/killswitch.sh

# Clean up when the tunnel goes down
PreDown = ip route del 192.168.0.0/16 || true
PreDown = ip route del 172.16.0.0/12 || true
PreDown = ip route del 10.0.0.0/8 || true

[Peer]
PublicKey = 123123123123123123123123123123123123=
AllowedIPs = 0.0.0.0/0
Endpoint = 222.333.44.55:51820
